<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>Penel Travel agensy</title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="Free HTML Templates" name="keywords">';
echo '<meta content="Free HTML Templates" name="description">';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/favicon.ico" rel="icon">';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.gstatic.com">';
echo '<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">';
echo '';
echo '<!-- Font Awesome -->';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '<link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet">';
echo '</head>';
echo '';
echo '<body>';
echo '<!-- Topbar Start -->';
echo '<div class="container-fluid bg-light pt-3 d-none d-lg-block">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">';
echo '<div class="d-inline-flex align-items-center">';
echo '<p><i class="fa fa-envelope mr-2"></i>alazargizachew12@gmail.com</p>';
echo '<p class="text-body px-3">|</p>';
echo '<p><i class="fa fa-phone-alt mr-2"></i>+251935480629</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 text-center text-lg-right">';
echo '<div class="d-inline-flex align-items-center">';
echo '<a class="text-primary px-3" href="">';
echo '<i class="fab fa-facebook-f"></i>';
echo '</a>';
echo '<a class="text-primary px-3" href="">';
echo '<i class="fab fa-twitter"></i>';
echo '</a>';
echo '<a class="text-primary px-3" href="">';
echo '<i class="fab fa-linkedin-in"></i>';
echo '</a>';
echo '<a class="text-primary px-3" href="">';
echo '<i class="fab fa-instagram"></i>';
echo '</a>';
echo '<a class="text-primary pl-3" href="">';
echo '<i class="fab fa-youtube"></i>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Topbar End -->';
echo '';
echo '';
echo '<!-- Navbar Start -->';
echo '<div class="container-fluid position-relative nav-bar p-0">';
echo '<div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">';
echo '<nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg py-3 py-lg-0 pl-3 pl-lg-5">';
echo '<a href="" class="navbar-brand">';
echo '<h1 class="m-0 text-primary"><span class="text-dark">TRAVEL</span>ER</h1>';
echo '</a>';
echo '<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">';
echo '<div class="navbar-nav ml-auto py-0">';
echo '<a href="index.html" class="nav-item nav-link">Home</a>';
echo '<a href="about.html" class="nav-item nav-link">About</a>';
echo '<a href="service.html" class="nav-item nav-link">Services</a>';
echo '<a href="package.html" class="nav-item nav-link">Tour Packages</a>';
echo '<a href="Sign up1.html" class="nav-item nav-link">Sign up</a>';
echo '<a href="contact.php" class="nav-item nav-link active">Contact</a>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '<!-- Navbar End -->';
echo '';
echo '';
echo '<!-- Header Start -->';
echo '<div class="container-fluid page-header">';
echo '<div class="container">';
echo '<div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">';
echo '<h3 class="display-4 text-white text-uppercase">Contact</h3>';
echo '<div class="d-inline-flex text-white">';
echo '<p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>';
echo '<i class="fa fa-angle-double-right pt-1 px-3"></i>';
echo '<p class="m-0 text-uppercase">Contact</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Header End -->';
echo '';
echo '';
echo '<!-- Booking Start -->';
echo '<div class="container-fluid booking mt-5 pb-5">';
echo '<div class="container pb-5">';
echo '<div class="bg-light shadow" style="padding: 30px;">';
echo '<div class="row align-items-center" style="min-height: 60px;">';
echo '<div class="col-md-10">';
echo '<div class="row">';
echo '<div class="col-md-3">';
echo '<div class="mb-3 mb-md-0">';
echo '<select class="custom-select px-4" style="height: 47px;">';
echo '<option selected>Destination</option>';
echo '<option value="1">Gondar </option>';
echo '<option value="2">Bahir Dar </option>';
echo '<option value="3">Axum </option>';
echo '<option value="4">Harar </option>';
echo '<option value="5">Addis ababa </option>';
echo '<option value="6">Nazret </option>';
echo '<option value="7">Adwa </option>';
echo '<option value="8">Jinka </option>';
echo '<option value="9">Lalibela </option>';
echo '<option value="10">Ather place </option>';
echo '</select>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-3">';
echo '<div class="mb-3 mb-md-0">';
echo '<div class="date" id="date1" data-target-input="nearest">';
echo '<input type="text" class="form-control p-4 datetimepicker-input" placeholder="Depart Date" data-target="#date1" data-toggle="datetimepicker"/>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-3">';
echo '<div class="mb-3 mb-md-0">';
echo '<div class="date" id="date2" data-target-input="nearest">';
echo '<input type="text" class="form-control p-4 datetimepicker-input" placeholder="Return Date" data-target="#date2" data-toggle="datetimepicker"/>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-3">';
echo '<div class="mb-3 mb-md-0">';
echo '<select class="custom-select px-4" style="height: 47px;">';
echo '<option selected>Duration</option>';
echo '<option value="1"03:00</option>';
echo '<option value="2">05:00</option>';
echo '<option value="3">07:00</option>';
echo '<option value="4">Ather duration </option>';
echo '</select>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-2">';
echo '<button class="btn btn-primary btn-block" type="submit" style="height: 47px; margin-top: -2px;">Submit</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Booking End -->';
echo '';
echo '';
echo '<!-- Contact Start -->';
echo '<div class="container-fluid py-5">';
echo '<div class="container py-5">';
echo '<div class="text-center mb-3 pb-3">';
echo '<h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Contact</h6>';
echo '<h1>Contact For Any Query</h1>';
echo '</div>';
echo '<div class="row justify-content-center">';
echo '<div class="col-lg-8">';
echo '<div class="contact-form bg-white" style="padding: 30px;">';
echo '<div id="success"></div>';
echo '<form name="sentMessage" id="contactForm" novalidate="novalidate">';
echo '<div class="form-row">';
echo '<div class="control-group col-sm-6">';
echo '<input type="text" class="form-control p-4" id="name" placeholder="Your Name"';
echo 'required="required" data-validation-required-message="Please enter your name" />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '<div class="control-group col-sm-6">';
echo '<input type="email" class="form-control p-4" id="email" placeholder="Your Email"';
echo 'required="required" data-validation-required-message="Please enter your email" />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '</div>';
echo '<div class="control-group">';
echo '<input type="text" class="form-control p-4" id="subject" placeholder="Subject"';
echo 'required="required" data-validation-required-message="Please enter a subject" />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '<div class="control-group">';
echo '<textarea class="form-control py-3 px-4" rows="5" id="message" placeholder="Message"';
echo 'required="required"';
echo 'data-validation-required-message="Please enter your message"></textarea>';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '<div class="text-center">';
echo '<button class="btn btn-primary py-3 px-4" type="submit" id="sendMessageButton">Send Message</button>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Contact End -->';
echo '';
echo '';
echo '<!-- Footer Start -->';
echo '<div class="container-fluid bg-dark text-white-50 py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">';
echo '<div class="row pt-5">';
echo '<div class="col-lg-3 col-md-6 mb-5">';
echo '<a href="" class="navbar-brand">';
echo '<h1 class="text-primary"><span class="text-white">TRAVEL</span>ER</h1>';
echo '</a>';
echo '<p>Sed ipsum clita tempor ipsum ipsum amet sit ipsum lorem amet labore rebum lorem ipsum dolor. No sed vero lorem dolor dolor</p>';
echo '<h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Follow Us</h6>';
echo '<div class="d-flex justify-content-start">';
echo '<a class="btn btn-outline-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-outline-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-outline-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>';
echo '<a class="btn btn-outline-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 mb-5">';
echo '<h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Destinations</h5>';
echo '<div class="d-flex flex-column justify-content-start">';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Lalibela</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Gondar</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Bahir Dar</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Axum</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Harar</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Addis ababa</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Nazret</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Adwa</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Jinka</a>';
echo '<a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Ather place</a>';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 mb-5">';
echo '<h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Usefull Links</h5>';
echo '<div class="d-flex flex-column justify-content-start">';
echo '<a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About</a>';
echo '<a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Destination</a>';
echo '<a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Services</a>';
echo '<a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Packages</a>';
echo '<a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Guides</a>';
echo '<a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Testimonial</a>';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 mb-5">';
echo '<h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Contact Us</h5>';
echo '<p><i class="fa fa-map-marker-alt mr-2"></i>6 Street, Addis Ababa</p>';
echo '<p><i class="fa fa-phone-alt mr-2"></i>+251935480629 & +251935480629</p>';
echo '<p><i class="fa fa-envelope mr-2"></i>alazargizachew@gmail.com</p>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">';
echo '<div class="row">';
echo '<div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">';
echo '<p class="m-0 text-white-50"> A new project by Alazar Gizachew 2023.</a>';
echo '</p>';
echo '</div>';
echo '<div class="col-lg-6 text-center text-md-right">';
echo '<p class="m-0 text-white-50">Designed by AMG Business group</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Footer End -->';
echo '';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>';
echo '';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '<script src="lib/tempusdominus/js/moment.min.js"></script>';
echo '<script src="lib/tempusdominus/js/moment-timezone.min.js"></script>';
echo '<script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>';
echo '';
echo '<!-- Contact Javascript File -->';
echo '<script src="mail/jqBootstrapValidation.min.js"></script>';
echo '<script src="mail/contact.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '</body>';
echo '';
echo '</html>';
?>